name: 'vdl_tilgangsstyring'
version: '0.1.0'
config-version: 2

vars:
  policy_schema: policies

profile: "vdl_tilgangsstyring_profile"

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]
macro-paths: ["macros"]

require-dbt-version: ">=1.0.0"


models:
  +persist_docs:
    relation: true
    columns: true
  vdl_tilgangsstyring:
    app:
      +schema: app
    policies:
      +schema: policies