id: tilgangsstyring

databases:
  - name: tilgangsstyring
    transient: false
    data_retention_time_in_days: 90
    schemas:
      - name: app
      - name: policies
      - name: oebs
      - name: csv
  - name: snowflake_users
    transient: false
    data_retention_time_in_days: 90
    schemas:
      - name: account_usage

roles:
  - name: snowflake_users_reader
  - name: tilgangsstyring_developer
  - name: tilgangsstyring_admin

warehouses:
  - name: tilgangsstyring_app

grants:
  - role: snowflake_users_reader
    warehouses:
      - tilgangsstyring_app
    write_on_schemas:
      - snowflake_users.account_usage
    to_roles:
      - tilgangsstyring_developer

  - role: tilgangsstyring_developer
    warehouses:
      - tilgangsstyring_app
    write_on_schemas:
      - tilgangsstyring.app
      - tilgangsstyring.policies
      - tilgangsstyring.csv
      - tilgangsstyring.oebs

  - role: tilgangsstyring_admin
    warehouses:
      - tilgangsstyring_app
    read_on_schemas:
      - tilgangsstyring.policies
    to_roles:
      - regnskap_transformer
      - faktura_transformer
